# Autograd engine

In [1]:
import torch

In [2]:
x = torch.tensor([2.0, 3.0])

In [3]:
y = torch.tensor([8.0, 12.0])

In [4]:
params = torch.tensor([2.0, 2.0], requires_grad=True)
params

tensor([2., 2.], requires_grad=True)

In [5]:
M = x * params
M

tensor([4., 6.], grad_fn=<MulBackward0>)

In [6]:
L = torch.mean(
    (y - M)**2
)
L

tensor(26., grad_fn=<MeanBackward0>)

In [7]:
L.backward()

In [8]:
params.grad

tensor([ -8., -18.])

In [9]:
LEARNING_RATE = 0.1

In [10]:
with torch.no_grad():
    params = params - LEARNING_RATE * params.grad
params

tensor([2.8000, 3.8000])

In [11]:
params.requires_grad_(True)
params

tensor([2.8000, 3.8000], requires_grad=True)

In [12]:
M = x * params
M

tensor([ 5.6000, 11.4000], grad_fn=<MulBackward0>)

In [13]:
L = torch.mean(
    (y - M)**2
)
L

tensor(3.0600, grad_fn=<MeanBackward0>)